# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1255c8eb3a0719f7bbc70f4f65b739929925062f72282f1d4683aaaa7247bb5c168e23809f6ab081c1c6de4cf98703cd6770a58de7cae0206ab4e6d847e7b9b7

test:
  secret_key_base: ff2fe42c98c5b5d7cbcc402e583c68ed434118c6fa0009567619a72286d8ebc4d95f48a7262d0d9abe2ec927abb7c009c42c42587a3cac73fe98b14224424e57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
